# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {M:/Lab 4/lab4/lab4.cache/wt} [current_project]
set_property parent.project_path {M:/Lab 4/lab4/lab4.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {m:/Lab 4/lab4/lab4.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {M:/Lab 4/uP_src/Data_mem.v}
  {M:/Lab 4/uP_src/EX_Mem_PR.v}
  {M:/Lab 4/uP_src/EX_stage.v}
  {M:/Lab 4/uP_src/ID_EX_PR.v}
  {M:/Lab 4/uP_src/ID_stage.v}
  {M:/Lab 4/uP_src/IF_ID_PR.v}
  {M:/Lab 4/uP_src/IF_stage.v}
  {M:/Lab 4/uP_src/Instruct_mem.v}
  {M:/Lab 4/uP_src/Mem_stage.v}
  {M:/Lab 4/uP_src/uP16_top.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{M:/Lab 4/uP16_top.xdc}}
set_property used_in_implementation false [get_files {{M:/Lab 4/uP16_top.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top uP16_top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef uP16_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file uP16_top_utilization_synth.rpt -pb uP16_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
